### ISSUE TITLE
Problem with XFCE 4 panel colors

### ISSUE THREAD

**Issue by ramzydoni** [B00merang-Project/Windows-10#128] opened 2018-06-05 15:10 UTC
i try install theme windwos 10 in my xfce mint 18 & xubuntu 
But the result was grim probleme panal is white (audio+wifi)
http://i.imgur.com/2peo19C.png
pls fix it thank you

**Comment by Elbullazul** [comment] 2018-06-05 17:48
we are aware of the issue and will publish a fix as soon as possible. Thank you for your feedback

**Comment by Elbullazul** [comment] 2018-06-05 17:51
also, duplicate of #116

**Closed by Elbullazul** 2018-06-05 17:51 UTC
Labels: XFCE
